/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#4d444f",
        "tertiary-container": "#7d5693",
        "surface": "#fff7ff",
        "primary-fixed": "#f8d8ff",
        "on-primary-container": "#f9dbff",
        "surface-dim": "#e0d7e5",
        "outline-variant": "#d0c2d0",
        "secondary-fixed-dim": "#e6b5f9",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#f5d9ff",
        "tertiary": "#643e79",
        "surface-container-high": "#efe5f4",
        "on-background": "#1e1a24",
        "tertiary-fixed-dim": "#e3b6fa",
        "surface-container-low": "#faf0ff",
        "error": "#ba1a1a",
        "on-surface": "#1e1a24",
        "secondary": "#784e8a",
        "on-secondary-fixed": "#2f0642",
        "surface-container": "#f4eaf9",
        "outline": "#7f7480",
        "surface-container-highest": "#e9dfee",
        "on-secondary-container": "#6f4681",
        "on-tertiary-fixed": "#2d0743",
        "secondary-container": "#ecbaff",
        "on-tertiary-container": "#f6dbff",
        "surface-tint": "#7f4796",
        "primary-fixed-dim": "#ebb2ff",
        "on-primary-fixed": "#320047",
        "on-error": "#ffffff",
        "surface-variant": "#e9dfee",
        "inverse-surface": "#342e39",
        "on-primary": "#ffffff",
        "surface-bright": "#fff7ff",
        "primary": "#6d3684",
        "on-tertiary-fixed-variant": "#5c3771",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#f7d8ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#874f9e",
        "inverse-primary": "#ebb2ff",
        "inverse-on-surface": "#f7edfc",
        "on-secondary-fixed-variant": "#5e3670",
        "on-primary-fixed-variant": "#652f7c",
        "background": "#fff7ff",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "margin-mobile": "16px",
        "unit": "4px",
        "lg": "24px",
        "md": "16px",
        "gutter": "24px",
        "container-max": "1440px",
        "sm": "8px",
        "xl": "48px"
      },
      fontFamily: {
        "label-md": ["Work Sans"],
        "display-lg-mobile": ["Manrope"],
        "label-sm": ["Work Sans"],
        "display-lg": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-lg": ["Work Sans"],
        "headline-md": ["Manrope"],
        "body-md": ["Work Sans"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "display-lg-mobile": ["36px", {"lineHeight": "42px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
